# -- Site Configuration --
theme = "congo"
baseURL = "/"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 0
title = "Worth Choosing"

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true
