[[main]]
  name = "Start Here"
  pageRef = "start-here"
  weight = 10

[[main]]
  name = "Our Vision"
  pageRef = "vivid-vision"
  weight = 20

[[main]]
  name = "Our Values"
  pageRef = "values"
  weight = 30

[[main]]
  name = "Reach Out"
  pageRef = "contact"
  weight = 40

[[footer]]
  name = "Our Vision"
  pageRef = "vivid-vision"
  weight = 10

[[footer]]
  name = "Our Values"
  pageRef = "values"
  weight = 20

[[footer]]
  name = "Gatherings"
  pageRef = "/gatherings/"
  weight = 25

[[footer]]
  name = "Partnership"
  pageRef = "partnership"
  weight = 30

[[footer]]
  name = "Advisory"
  pageRef = "/advisory/"
  weight = 35

[[footer]]
  name = "Reach Out"
  pageRef = "contact"
  weight = 40

[[footer]]
  name = "Subscribe"
  pageRef = "subscribe"
  weight = 50
