[build]
  publish = "public"
  command = "rm -rf themes/congo && git clone --depth 1 --branch v2.13.0 https://github.com/jpanther/congo.git themes/congo && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.154.4"

[context.production.environment]
  HUGO_ENV = "production"
